### ISSUE TITLE
Export repository domain name to config file

### ISSUE THREAD

**Issue by aubincleme** [Thooms/issues-reminder#1]
In order to permit issues retrieval from different Git domains (such as [git.framasoft.org](http://git.framasoft.org)), could it be possible to export this option to `settings.yaml` ?

**Comment by Thooms** [comment]
I'm on it, but you'll have to code a bit for each provider you wish to use. By that I mean that not everyone has a cool API like GitHub :)

Though, I'll code the thing for GH, and you'll be free for the rest!

**Comment by Thooms** [comment]
Also, depends on #3 and #4.

**Comment by Thooms** [comment]
ping @aubincleme are you satisfied now?

**Comment by aubincleme** [comment]
Yaaay thanks ! :D
